// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDswy9wShkZGne6G0bMOoiiyR_gj3a6dzU',
    appId: '1:732438605479:web:16e1e35a2d2de934a53582',
    messagingSenderId: '732438605479',
    projectId: 'unidesk-c5bfb',
    authDomain: 'unidesk-c5bfb.firebaseapp.com',
    storageBucket: 'unidesk-c5bfb.firebasestorage.app',
    measurementId: 'G-S2CSVB8TTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDd4n0-twed2fdOQWRVt8JaCgAYZmuWOo',
    appId: '1:732438605479:android:cc51ceb50c3ddd4fa53582',
    messagingSenderId: '732438605479',
    projectId: 'unidesk-c5bfb',
    storageBucket: 'unidesk-c5bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZdBS6cgiHEBpOEP2vQmvKFeT0Ecmt0LM',
    appId: '1:732438605479:ios:a12e83539230ffbca53582',
    messagingSenderId: '732438605479',
    projectId: 'unidesk-c5bfb',
    storageBucket: 'unidesk-c5bfb.firebasestorage.app',
    iosBundleId: 'com.example.unidesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZdBS6cgiHEBpOEP2vQmvKFeT0Ecmt0LM',
    appId: '1:732438605479:ios:a12e83539230ffbca53582',
    messagingSenderId: '732438605479',
    projectId: 'unidesk-c5bfb',
    storageBucket: 'unidesk-c5bfb.firebasestorage.app',
    iosBundleId: 'com.example.unidesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDswy9wShkZGne6G0bMOoiiyR_gj3a6dzU',
    appId: '1:732438605479:web:1e56f21d13d50693a53582',
    messagingSenderId: '732438605479',
    projectId: 'unidesk-c5bfb',
    authDomain: 'unidesk-c5bfb.firebaseapp.com',
    storageBucket: 'unidesk-c5bfb.firebasestorage.app',
    measurementId: 'G-QBJCP317DQ',
  );
  
}
