class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'login': 'Login',
      'enter_id': 'Enter Your ID @st.aabu.edu.jo',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'welcome': 'Welcome to UniDesk',
      'welcome_back': 'Welcome back,',
      'invalid_token': 'Invalid token',
      'logged_in_as': 'Logged in as: ',
      'please_login_again': 'Please login again.',
      'logout': 'Logout',
      'back_to_login': 'Back to login',
      'please_enter_id_password': 'Please enter your ID and password.',
      'home': 'Home',
      'courses': 'Courses',
      'schedule': 'Schedule',
      'profile': 'Profile',
      'current_courses': 'Current Courses',
      'technical_support': 'Technical Support',
      'electronic_payment': 'Electronic Payment',
      'current_semester': 'Current Semester',
      'advertisements': 'Advertisements',
      'completion_percentage': 'Completion Percentage',
      'credits': 'Credits',
      'gpa': 'GPA',
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'enter_id': 'أدخل إيميلك الجامعي',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'welcome': 'أهلًا بك في UniDesk',
      'welcome_back': 'مرحبًا بعودتك،',
      'invalid_token': 'رمز غير صحيح',
      'logged_in_as': 'تم تسجيل الدخول كـ: ',
      'please_login_again': 'يرجى تسجيل الدخول مرة أخرى.',
      'logout': 'تسجيل الخروج',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'please_enter_id_password': 'يرجى إدخال الرقم الجامعي وكلمة المرور.',
      'home': 'الرئيسية',
      'courses': 'المواد',
      'schedule': 'الجدول',
      'profile': 'الملف الشخصي',
      'current_courses': 'المواد الحالية',
      'technical_support': 'الدعم الفني',
      'electronic_payment': 'الدفع الإلكتروني',
      'current_semester': 'الفصل الحالي',
      'advertisements': 'الإعلانات',
      'completion_percentage': 'نسبة الإنجاز',
      'credits': 'الساعات',
      'gpa': 'المعدل',
    },
  };
}
