class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'login': 'Login',
      'enter_id': 'Enter your university email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'welcome': 'Welcome to UniDesk',
      'welcome_back': 'Welcome back,',
      'invalid_token': 'Invalid token',
      'logged_in_as': 'Logged in as: ',
      'please_login_again': 'Please login again.',
      'logout': 'Logout',
      'back_to_login': 'Back to login',
      'please_enter_id_password': 'Please enter your email and password.',
      'home': 'Home',
      'courses': 'Courses',
      'schedule': 'Schedule',
      'profile': 'Profile',
      'current_courses': 'Current Courses',
      'technical_support': 'Technical Support',
      'electronic_payment': 'Electronic Payment',
      'current_semester': 'Current Semester',
      'annoucements': 'Annoucements',
      'completion_percentage': 'Completion Percentage',
      'credits': 'Credits',
      'gpa': 'GPA',
      'absence_record': 'Absence Record',
      'attendance_policy': 'Register Attendance',
      'request_excuse': 'Request Excuse',
      'academic_progress': 'Academic Progress',
      'completed_courses': 'Completed Courses',
      'grades': 'Grades',
      'not_available': 'N/A',
      'gpa_calc': 'GPA Calculator',
      'fall': 'Fall',
      'spring': 'Spring',
      'summer': 'Summer',
      'no_data': 'No available data to display',
      'previous_semesters': 'Previous Semesters',
      'id': 'ID',
      'refresh': 'Refresh',
      'failed_to_load_profile': 'Failed to load profile, please try again.',
      'no_profile_data': 'No profile data available.',
      'student_id': 'Student ID',
      'email': 'Email',
      'major': 'Major',
      'year': 'Year',
      'credits_completed': 'Credits Completed',
      'total_hours': 'Total Hours',
      'student_information': 'Student Information',
      'personal_information': "Personal Information",
      'permanent_address': 'Permanent Address',
      'phone_number_1': 'Phone Number 1',
      'phone_number_2': 'Phone Number 2',
      'identifier_1': 'Identifier 1',
      'identifier_2': 'Identifier 2',
      'phone_number_of_identifier_1': 'Phone Number of Identifier 1',
      'phone_number_of_identifier_2': 'Phone Number of Identifier 2',
      'save_changes': 'Save Changes',
      'changes_saved': 'Changes saved successfully.',
      'cancel': 'Cancel',
      'personal_email': 'Personal Email',
      'retry': 'Retry',
      'no_grades': 'No grades available.',
      'instructor': 'Instructor',
      'sunday': 'Sunday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'files': 'Files',
      'attendance': 'Attendance',
      'assignments': 'Assignments',
      'phone_number': 'Phone Number',
      'phone': 'Phone',
      'instructor_info': 'Instructor Info',
      'refreshing_courses': 'Refreshing courses...',
      'failed_to_load_courses': 'Failed to load courses',
      'failed_to_load_academic_progress': 'Failed to load academic progress',
      'no_courses_enrolled': 'No courses enrolled',
      'no_progress_data': 'No academic progress data available',
      'refreshing_home_data': 'Refreshing home data...',
      'failed_to_load_home': 'Failed to load home page',
      'instructor_fallback_name': 'Instructor',
      'no_upcoming_lecture': 'No upcoming lecture',
      'schedule_unavailable': 'Schedule unavailable',
      'room_unavailable': 'Room unavailable',
      'todays_overview': "Today's Overview",
      'next_lecture': 'Next Lecture',
      'quick_actions': 'Quick Actions',
      'my_courses': 'My Courses',
      'lectures_today': 'Lectures Today',
      'today_attendance': 'Today Attendance',
      'students_absent': 'Students Absent',
      'upload_files': 'Upload\nFiles',
      'take_attendance': 'Take\nAttendance',
      'view_reports': 'View\nReports',
      'new_announcement': 'New\nAnnouncement',
      'announcements_title': 'Announcements',
      'announcements_subtitle_empty':
          'Choose a course and section to publish updates.',
      'announcements_subtitle_count': 'announcements',
      'announcement_new': 'New Announcement',
      'announcement_form_title': 'Create Announcement',
      'announcement_recent_title': 'Recent Announcements',
      'announcement_course': 'Course',
      'announcement_section': 'Section',
      'announcement_choose_course': 'Choose a course',
      'announcement_choose_section': 'Choose a section',
      'announcement_type': 'Type',
      'announcement_title_label': 'Title',
      'announcement_title_hint': 'Project Guidelines',
      'announcement_description_label': 'Description',
      'announcement_description_hint':
          'Please read the project guidelines carefully.',
      'announcement_publish': 'Publish Announcement',
      'announcement_publishing': 'Publishing...',
      'announcement_created': 'Announcement created successfully.',
      'announcement_empty': 'No announcements for this section yet.',
      'announcement_select_target':
          'Select a course and section before publishing.',
      'announcement_required_course': 'Please choose a course.',
      'announcement_required_section': 'Please choose a section.',
      'announcement_required_title': 'Please enter a title.',
      'announcement_required_description': 'Please enter a description.',
      'announcement_retry': 'Retry',
      'announcement_load_failed': 'Failed to load announcements',
      'announcement_type_general': 'General',
      'announcement_type_assignment': 'Assignment',
      'announcement_type_exam': 'Exam',
      'announcement_type_project_guidelines': 'Project Guidelines',
      'announcement_type_new_assignment': 'New Assignment',
      'announcement_type_class_cancelled': 'Class Cancelled',
      'announcement_type_exam_schedule': 'Exam Schedule',
      'announcement_date_unavailable': 'Date unavailable',
      'section': 'Section',
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'enter_id': 'أدخل بريدك الجامعي',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'welcome': 'مرحباً بك في UniDesk',
      'welcome_back': 'مرحباً بعودتك،',
      'invalid_token': 'رمز غير صالح',
      'logged_in_as': 'تم تسجيل الدخول بحساب: ',
      'please_login_again': 'يرجى تسجيل الدخول مرة أخرى.',
      'logout': 'تسجيل الخروج',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'please_enter_id_password': 'يرجى إدخال معرفك وكلمة المرور.',
      'home': 'الرئيسية',
      'courses': 'المقررات',
      'schedule': 'الجدول',
      'profile': 'الملف الشخصي',
      'current_courses': 'المقررات الحالية',
      'technical_support': 'الدعم الفني',
      'electronic_payment': 'الدفع الإلكتروني',
      'current_semester': 'الفصل الحالي',
      'annoucements': 'الإعلانات',
      'completion_percentage': 'نسبة الإنجاز',
      'credits': 'الساعات المعتمدة',
      'gpa': 'المعدل',
      'absence_record': 'سجل الغياب',
      'attendance_policy': 'تسجيل الحضور',
      'request_excuse': 'طلب عذر',
      'academic_progress': 'التقدم الأكاديمي',
      'completed_courses': 'المقررات المنجزة',
      'grades': 'الدرجات',
      'not_available': 'غير متاح',
      'gpa_calc': 'حاسبة المعدل',
      'fall': 'الخريف',
      'spring': 'الربيع',
      'summer': 'الصيف',
      'no_data': 'لا توجد بيانات متاحة للعرض',
      'previous_semesters': 'الفصول السابقة',
      'id': 'رقم المقرر',
      'refresh': 'تحديث',
      'failed_to_load_profile': 'فشل تحميل الملف الشخصي، يرجى المحاولة مجدداً.',
      'no_profile_data': 'لا توجد بيانات للملف الشخصي.',
      'student_id': 'رقم الطالب',
      'email': 'البريد الإلكتروني',
      'major': 'التخصص',
      'year': 'السنة',
      'credits_completed': 'الساعات المكتملة',
      'total_hours': 'إجمالي الساعات',
      'student_information': 'بيانات الطالب',
      'personal_information': 'المعلومات الشخصية',
      'permanent_address': 'العنوان الدائم',
      'phone_number_1': 'رقم الهاتف 1',
      'phone_number_2': 'رقم الهاتف 2',
      'identifier_1': 'المعرّف 1',
      'identifier_2': 'المعرّف 2',
      'phone_number_of_identifier_1': 'رقم هاتف المعرّف 1',
      'phone_number_of_identifier_2': 'رقم هاتف المعرّف 2',
      'save_changes': 'حفظ التغييرات',
      'changes_saved': 'تم حفظ التغييرات بنجاح.',
      'cancel': 'إلغاء',
      'personal_email': 'البريد الشخصي',
      'retry': 'إعادة المحاولة',
      'no_grades': 'لا توجد درجات متاحة.',
      'instructor': "المدرس",
      'sunday': 'الأحد',
      'monday': 'الأثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الاربعاء',
      'thursday': 'الخميس',
      'files': 'المقررات',
      'attendance': 'الحضور',
      'assignments': 'الواجبات',
      'phone_number': 'رقم الهاتف',
      'phone': 'رقم الهاتف',
      'instructor_info': 'معلومات المدرس',
      'refreshing_courses': 'جاري تحديث المواد...',
      'failed_to_load_courses': 'فشل تحميل المواد',
      'failed_to_load_academic_progress': 'فشل تحميل التقدم الأكاديمي',
      'no_courses_enrolled': 'لا توجد مواد مسجلة',
      'no_progress_data': 'لا توجد بيانات تقدم أكاديمي',
      'refreshing_home_data': 'جاري تحديث البيانات...',
      'failed_to_load_home': 'فشل تحميل الصفحة الرئيسية',
      'instructor_fallback_name': 'المدرس',
      'no_upcoming_lecture': 'لا توجد محاضرة قادمة',
      'schedule_unavailable': 'الجدول غير متاح',
      'room_unavailable': 'القاعة غير متاحة',
      'todays_overview': 'نظرة اليوم',
      'next_lecture': 'المحاضرة القادمة',
      'quick_actions': 'الإجراءات السريعة',
      'my_courses': 'موادي',
      'lectures_today': 'محاضرات اليوم',
      'today_attendance': 'حضور اليوم',
      'students_absent': 'الطلاب الغائبون',
      'upload_files': 'رفع\nالملفات',
      'take_attendance': 'تسجيل\nالحضور',
      'view_reports': 'عرض\nالتقارير',
      'new_announcement': 'إعلان\nجديد',
      'announcements_title': 'الإعلانات',
      'announcements_subtitle_empty': 'اختر المادة والشعبة لنشر التحديثات.',
      'announcements_subtitle_count': 'إعلانات',
      'announcement_new': 'إعلان جديد',
      'announcement_form_title': 'إنشاء إعلان',
      'announcement_recent_title': 'الإعلانات الأخيرة',
      'announcement_course': 'المادة',
      'announcement_section': 'الشعبة',
      'announcement_choose_course': 'اختر مادة',
      'announcement_choose_section': 'اختر شعبة',
      'announcement_type': 'النوع',
      'announcement_title_label': 'العنوان',
      'announcement_title_hint': 'إرشادات المشروع',
      'announcement_description_label': 'الوصف',
      'announcement_description_hint': 'يرجى قراءة إرشادات المشروع بعناية.',
      'announcement_publish': 'نشر الإعلان',
      'announcement_publishing': 'جاري النشر...',
      'announcement_created': 'تم إنشاء الإعلان بنجاح.',
      'announcement_empty': 'لا توجد إعلانات لهذه الشعبة بعد.',
      'announcement_select_target': 'اختر المادة والشعبة قبل النشر.',
      'announcement_required_course': 'يرجى اختيار مادة.',
      'announcement_required_section': 'يرجى اختيار شعبة.',
      'announcement_required_title': 'يرجى إدخال العنوان.',
      'announcement_required_description': 'يرجى إدخال الوصف.',
      'announcement_retry': 'إعادة المحاولة',
      'announcement_load_failed': 'فشل تحميل الإعلانات',
      'announcement_type_general': 'عام',
      'announcement_type_assignment': 'واجب',
      'announcement_type_exam': 'امتحان',
      'announcement_type_project_guidelines': 'إرشادات المشروع',
      'announcement_type_new_assignment': 'واجب جديد',
      'announcement_type_class_cancelled': 'إلغاء المحاضرة',
      'announcement_type_exam_schedule': 'جدول الامتحان',
      'announcement_date_unavailable': 'التاريخ غير متاح',
      'section': 'الشعبة',
    },
  };
}
