class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'login': 'Login',
      'enter_id': 'Enter Your ID @st.aabu.edu.jo',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'welcome': 'Welcome to UniDesk',
      'welcome_back': 'Welcome back,',
      'invalid_token': 'Invalid token',
      'logged_in_as': 'Logged in as: ',
      'please_login_again': 'Please login again.',
      'logout': 'Logout',
      'back_to_login': 'Back to login',
      'please_enter_id_password': 'Please enter your ID and password.',
      'home': 'Home',
      'courses': 'Courses',
      'schedule': 'Schedule',
      'profile': 'Profile',
      'current_courses': 'Current Courses',
      'technical_support': 'Technical Support',
      'electronic_payment': 'Electronic Payment',
      'current_semester': 'Current Semester',
      'annoucements': 'Annoucements',
      'completion_percentage': 'Completion Percentage',
      'credits': 'Credits',
      'gpa': 'GPA',
      'absence_record': 'Absence Record',
      'attendance_policy': 'Attendance Policy',
      'request_excuse': 'Request Excuse',
      'academic_progress': 'Academic Progress',
      'completed_courses': 'Completed Courses',
      'grades': 'Grades',
      'not_available': 'N/A',
      'gpa_calc': 'GPA Calculator',
      'fall': 'Fall',
      'spring': 'Spring',
      'summer': 'Summer',
      'no_data': 'No available data to display',
      'previous_semesters': 'Previous Semesters',
      'id': 'ID',
      
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'enter_id': 'أدخل بريدك الجامعي',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'welcome': 'مرحباً بك في UniDesk',
      'welcome_back': 'مرحباً بعودتك،',
      'invalid_token': 'رمز غير صالح',
      'logged_in_as': 'تم تسجيل الدخول بحساب: ',
      'please_login_again': 'يرجى تسجيل الدخول مرة أخرى.',
      'logout': 'تسجيل الخروج',
      'back_to_login': 'العودة إلى تسجيل الدخول',
      'please_enter_id_password': 'يرجى إدخال معرفك وكلمة المرور.',
      'home': 'الرئيسية',
      'courses': 'المقررات',
      'schedule': 'الجدول',
      'profile': 'الملف الشخصي',
      'current_courses': 'المقررات الحالية',
      'technical_support': 'الدعم الفني',
      'electronic_payment': 'الدفع الإلكتروني',
      'current_semester': 'الفصل الحالي',
      'annoucements': 'الإعلانات',
      'completion_percentage': 'نسبة الإنجاز',
      'credits': 'الساعات المعتمدة',
      'gpa': 'المعدل',
      'absence_record': 'سجل الغياب',
      'attendance_policy': 'سياسة الحضور',
      'request_excuse': 'طلب عذر',
      'academic_progress': 'التقدم الأكاديمي',
      'completed_courses': 'المقررات المنجزة',
      'grades': 'الدرجات',
      'not_available': 'غير متاح',
      'gpa_calc': 'حاسبة المعدل',
      'fall': 'الخريف',
      'spring': 'الربيع',
      'summer': 'الصيف',
      'no_data': 'لا توجد بيانات متاحة للعرض',
      'previous_semesters': 'الفصول السابقة',
      'id': 'رقم المقرر',
    },
  };
}